title: Royal Technologies
description: MacBooks and Microsoft 365 solutions in Guyana with fast local support and easy ordering.

# GitHub Pages URL (NO custom domain)
url: https://taricohenry.github.io
baseurl: ""

collections_dir: collections
plugins: []
macbook_url: "/macbook-neo"
office_url: "/ms-office"
whatsapp_url: "https://wa.me/5926184703"
facebook_url: "https://www.facebook.com/people/Royal-Technologies/61574230534094/"
email_address: "sales@royaltechgy.com"
